### PR TITLE
merging file.data to opts.locals

### PR DESCRIPTION
**Pull request by otmjka**
Hi, i could not retrieve data from json file. did some changes.

### CODE REVIEW

**Comment by phated** [comment]
The only way that file.data exists is if something up the stream adds it.  In those situations, we don't want to merge, we want to take only the data passed.  If you are using something like gulp-data to add data per file and adding metadata from package.json on every file, you can do the extends in the gulp-data callback instead of adding logic to gulp-jade.

**Comment by otmjka** [comment]
Ok! I just want that gulp-jade and gulp-data works together properly. Or understand what I do wrong... can you see example:
https://github.com/otmjka/gulp-jade-test
there's I try to get "title" from test.jade.json and include it to test.jade. As result is empty "title" variable in jade template.

**Comment by phated** [comment]
I modified your example here: https://gist.github.com/phated/983d49312b80bfde754c

As you can see, the extend happens in gulp-data callback instead of inside gulp-jade.  I see that @colynb is suggesting an extend in the readme, but also suggests that you can just do an assignment.  I think the assignment keeps the module more pure, but that extra extend in gulp-data can be annoying.  I will consider this some more.  If anything, I wouldn't create a custom extend inside the module.

**Comment by otmjka** [comment]
thank you! you are right around.

**Pull request closed without merging**
