### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by shinnn**
[Jade](http://jade-lang.com/) v1.11.0 has been released. https://github.com/jadejs/jade/blob/master/History.md

I've looked the changelog through and there seems to be no breaking changes related to this plugin.

### CODE REVIEW

**Comment by shinnn** [comment]
:white_check_mark:  This PR passed all the tests. https://travis-ci.org/phated/gulp-jade/builds/69581408

**Comment by dajnz** [comment]
Yes, this is useful commit! I had an issue with old jade version in gulp-jade when try to use [multiline block code](https://github.com/jadejs/jade/issues/164). So I've updated my local deps manually.

**Comment by jonnyscholes** [comment]
Would be rad to see this merged :) multiline block code is super useful!

**Comment by phated** [comment]
This release looks stable (I typically let things simmer a few weeks).  I'll merge and bump

**Pull request merged**
