### PR TITLE
Upgraded through2 to 0.5.1

### PR DESCRIPTION
**Pull request by tomchentw**
Also changed callback style.

### CODE REVIEW

**Comment by phated** [comment]
I went through the code in https://www.npmjs.org/package/readable-stream as it relates to through2 and it doesn't seem to emit the error on the stream if passed to the callback.  Can you investigate further and pass the results along?  Thanks.

**Comment by tomchentw** [comment]
`through2^0.5.1` uses `readable-stream^1.0.27`
https://github.com/isaacs/readable-stream/blob/v1.0.27-1/lib/_stream_transform.js#L155 
And it can take error in the callback.

Another proof is that the test cases passes, right?

**Comment by phated** [comment]
Don't just point to a comment.  If you look at afterTransform at https://github.com/isaacs/readable-stream/blob/v1.0.27-1/lib/_stream_transform.js#L88-L111 you will see that the error is ignored.  I just looked at the transform tests at https://github.com/isaacs/readable-stream/blob/v1.0.27-1/test/simple/test-stream2-transform.js and none of them pass an error to the callback.

**Comment by yocontra** [comment]
Just tested this

``` js
stream = through.obj(function(chunk, enc, cb){ cb(new Error('damn')); })

stream.write(123); // throws error due to no listener, standard EE stuff

stream.on('error', function(err) {
  console.log('shit', err);
});

stream.write(123); // nothing thrown since we have a listener

// we get the log
```

so it seems like the cb err arg is working perfectly

**Comment by phated** [comment]
Looks like it is in read stream, which is inherited through duplex stream.

**Comment by yocontra** [comment]
@phated 

learn a lesson here

**Pull request merged**
