### PR TITLE
Add Markdown support

### PR DESCRIPTION
**Pull request by omarrr**
Hi,
I've added the marked dependency to the project to enable Markdown support on .jade files. Also added a test for it. Please review.

Cheers!

### CODE REVIEW

**Comment by phated** [comment]
Can't this be installed on a per-project basis?  I don't really like forcing this dependency on everyone, especially because it leads to adding all the modules to support the different filters.

**Comment by omarrr** [comment]
A per-project solution might be a better approach, however I have not been able to enable markdown cleanly without editing the gulp-jade pluging after install. 

It looks like jade requires the markdown plugin to be installed in a path relative to the jade executable. Since the jade executable is inside the `gulp-jade/node_modules` folder, I had to manually copy the `marked` module as well. Definitely not the way to go and the reason why I added the dependency to your module.

There might be an easier solution that I am not aware of. I'm still just getting my feet wet with gulp. Thanks!

**Comment by phated** [comment]
I just tested `marked` as a devDep alongside `gulp-jade` and it worked fine.  Not sure what the issue is.

**Comment by omarrr** [comment]
Sounds like it's a problem with my configuration if you were able to get it to work. That's good news and something for me to review. thanks!

**Comment by phated** [comment]
Alright. Going to close this for now. We can still discuss here if you can't get it working.

**Comment by bhongy** [comment]
Tested and it works as @phated said.

All you have to do is, `npm install --save-dev marked` in your project root (as adding another gulp plugins or node modules). Do not have to make any change to your gulpfile. Rerun gulp and it will compile jade templates with :markdown filters applied without error.

Same issue [here](https://github.com/gruntjs/grunt-contrib-jade/issues/38) in grunt-contrib-jade

@phated, if it would help, I can edit the readme file to include a quick guide on how to get [jade filters](http://jade-lang.com/reference/#filters) to work with gulp-jade. Please let me know if that sounds good.

**Comment by pudgereyem** [comment]
@bhongy I would appreciate a quick guide on how to get jade filters to work with gulp-jade. :+1:

**Pull request closed without merging**
