### PR TITLE
Async and Function Support

### PR DESCRIPTION
**Pull request by gtg092x**
This update allows users to pull template locals from a function both synchronously and asynchronously.

### CODE REVIEW

**Comment by phated** [comment]
This seems out of the scope of the gulp-jade module.  I am going to take some time to think about this.

**Comment by gtg092x** [comment]
Understand - any thoughts on the best way to achieve async support and maintain the proper scope?

**Comment by phated** [comment]
What is the proper scope you are looking for?

**Comment by gtg092x** [comment]
Blaine,

The need is around async locals that may be file dependent. This helps 
me render large sites statically that may need to do something like 
access web services or databases and might need different locals 
depending on the file.

Let me know if that helps.

**Comment by yocontra** [comment]
Big thumbs down on this. I'll post an alternative when I have my computer on hand

**Comment by yocontra** [comment]
``` js
var asyncDone = require('async-done');

gulp.task('templates', function(cb){
  doAsync(function(locals){
    var stream = gulp.src('files/*.jade')
      .pipe(jade(locals))
      .pipe(gulp.dest('stuff'));

    asyncDone(stream, cb);
  });
});
```

**Comment by phated** [comment]
Thanks @Contra, I think he wanted access to the filename to make the decision on what locals to include.

**Comment by yocontra** [comment]
Woops read this from a phone. Let me think about it a bit more and see if I can figure out an alternative

**Comment by yocontra** [comment]
Want to share more about your use case @gtg092x? Can I see what your task looks like with your changes implemented?

You could possibly do something like this:

``` js
var gif = require('gulp-if');

gulp.task('templates', function(cb){
    return gulp.src('files/*.jade')
      .pipe(gif('file1.jade', jade(locals1)))
      .pipe(gif('file2.jade', jade(locals2)))
      .pipe(gulp.dest('stuff'));
});
```

**Comment by gtg092x** [comment]
Eric, a really  straightforward example would be asynchronously getting the 
title of every page based on the filename. I can code up an example from a 
computer in a little bit but I think I can achieve what I need through your 
usage pattern here. Thanks for the advice.

I don't expect anyone to change their mind here so I will retract the pull 
request.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by yocontra** [comment]
@gtg092x I'm not 100% against your use case but I think we can solve it generically so we don't have to implement this same pattern in every single plugin.

``` js
gulp.src('files/*.jade')
  .pipe(wrapper(jade, function(file, cb){
    cb(null, opts);
  });
```

where wrapper is a module that constructs a new child stream per file using the arguments returned from the function?

**Comment by phated** [comment]
I agree with @Contra - I can't think of a way to do it with currently available gulp modules, but I think something with the API he suggested is needed because it isn't a problem specific to jade.

**Comment by colynb** [comment]
I've added a similar feature to gulp-swig, if it's not proper for gulp-jade then it's not proper for my plugin either.  It's set up so that if you have a template and an accompanying JSON file of the same name (ex. template.html, template.json) you can optionally include the data file and import it as local variables. If you can think of a way to achieve that in a decoupled way, I'll be happy to update my plugin.

**Comment by phated** [comment]
Closing in favor of a generic solution like @contra suggested

**Pull request closed without merging**
