### PR TITLE
upgrade pug

### PR DESCRIPTION
**Pull request by KiaraGrouwstra**
Ref #207

### CODE REVIEW

**Comment by phated** [comment]
Thanks @KiaraGrouwstra! Do the tests or anything need to change for the major breaking version? I'm in the process of revamping the repository structure and want to publish a major breaking change with this included soon(tm)

**Comment by philmayfield** [comment]
@phated just curious if you had an eta on this fix?  I'm mostly concerned about the CVE with pug.  Thanks!

**Comment by phated** [comment]
@philmayfield no timelines ever, this is open source and people have lives and paid work.

If you need to use a different version of pug, there's a plugin option for it (assuming the API interface is the same, as this PR claims).

**Comment by phated** [comment]
Released as 5.0.0

**Pull request closed without merging**
